server:
  port: 8082

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: order_db
    password: order_db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    config:
      label: master
      uri: http://localhost:8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
